disabled_rules:
  - trailing_whitespace
  - line_length
opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
included:
  - Sleev
  - SleevCore
  - SleevTests
excluded:
  - .build
  - DerivedData
